{{- range $key, $value := .Values.deployments}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eo-base-helm-chart.fullname" $ }}-{{ $key }}
  labels:
    {{- include "eo-base-helm-chart.labels" $ | nindent 4 }}
    component: {{ $key }}
spec:
  replicas: {{ $value.replicaCount }}
  selector:
    matchLabels:
      {{- include "eo-base-helm-chart.selectorLabels" $ | nindent 6 }}
      component: {{ $key }}
  template:
    metadata:
      labels:
        {{- include "eo-base-helm-chart.selectorLabels" $ | nindent 8 }}
        component: {{ $key }}
    spec:
      {{- include "eo-base-helm-chart.podTemplate" (dict "root" $ "name" $key "deployment" $value) | nindent 6 }}
{{- end }}
